services:
    angsym.twig_extension:
        class: Legionofmyown\AngsymBundle\Service\TwigExtension
        arguments: [@twig.extension.httpkernel]
        tags:
            - { name: twig.extension }

    angsym.form:
        class: Legionofmyown\AngsymBundle\Service\FormService
        arguments: [@form.factory]
